## 2.1.1 Getting Started

In [1]:
import torch

A tensor represents a (possibly multi-dimensional) array of numerical values. With one axis, a tensor is called a vector. With two axes, a tensor is called a matrix. With  𝑘>2  axes, we drop the specialized names and just refer to the object as a  𝑘th  order tensor.

In [2]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [3]:
x.shape

torch.Size([12])

In [4]:
x.numel()

12

In [5]:
#transform tensor x from a row vector with shape (12,) to a matrix with shape (3, 4). 
X = x.reshape(3,4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

 Fortunately, tensors can automatically work out one dimension given the rest. We invoke this capability by placing -1 for the dimension that we would like tensors to automatically infer.

In [6]:
x.reshape(-1,4)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [8]:
x.reshape(3,-1)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [9]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])



*   randomly sample the values for each element in a tensor from some probability distribution
*   The following snippet creates a tensor with shape (3, 4). Each of its elements is **randomly sampled from a standard Gaussian (normal) distribution** with a mean of 0 and a standard deviation of 1.


In [11]:
torch.randn(3,4)

tensor([[-2.5492,  0.3670,  0.4263, -1.9573],
        [-1.1777,  1.5129,  0.6241,  0.9568],
        [ 0.3574, -0.3624,  0.4376,  0.0885]])

In [12]:
torch.tensor([[2,1,4,3,],[1,2,3,4],[4,3,2,1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

## 2.1.2 Operations

In [13]:
x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,2,2])
x+y, x-y, x*y, x/y, x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [14]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

 

*   We can also concatenate multiple tensors together, stacking them end-to-end to form a larger tensor.
*   **rows (axis 0), columns(axis 1)**




In [15]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X,Y), dim=0), torch.cat((X,Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [16]:
#  binary tensor via logical statements.
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [18]:
X < Y

tensor([[ True, False,  True, False],
        [False, False, False, False],
        [False, False, False, False]])

In [17]:
#Summing all the elements in the tensor yields a tensor with only one element.
X.sum()

tensor(66.)

## 2.1.3 Broadcasting Mechanism

how to perform elementwise operations on two tensors of the same shape


1.   expand one or both arrays by copying elements appropriately so that after this transformation, the two tensors have the same shape
2.   carry out the elementwise operations on the resulting arrays.



In [19]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]), tensor([[0, 1]]))

In [20]:
#broadcast the entries of both matrices into a large matix
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## 2.1.4 Indexing and Slicing

In [21]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [22]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]), tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [23]:
X[1,2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [24]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## 2.1.5 Saving Memory


 X[:] = X + Y or X += Y to reduce the memory overhead of the operation.

In [25]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [28]:
before = id(Y)
Y += X
id(Y) == before

True

In [26]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 139652898043472
id(Z): 139652898043472


## 2.1.6 Conversion to Other Python Objects

In [29]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [30]:
# To convert a size-1 tensor to a Python scalar, invoke the item function or Python’s built-in functions.
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)