# 2.5. Automatic Differentiation

## 2.5.1. A Simple Example

In [ ]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [ ]:
x.requires_grad_(True)
x.grad

In [ ]:
y = 2*torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [ ]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [ ]:
x.grad == 4*x

tensor([True, True, True, True])

In [ ]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

## 2.5.2 Backward for Non-scalar Variabels


In [ ]:
x.grad.zero_()
y = x*x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

## 2.5.3. Detaching Computation


In [ ]:
x.grad.zero_()
y = x*x
u = y.detach()
z = u*x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [ ]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

## 2.5.4. Computing the Gradient of Python Control Flow

In [ ]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [ ]:
a = torch.randn(size=(), requires_grad=True) # tensor의 연산을 추적함
d = f(a)
d.backward() #연산이 끝난 후 , backward()를 호출하여 자동으로 모든 기울기를 계산함
#tensor에 대한 기울기(gradient)는 .grad 속성에 누적됨
# .detach()를 호출하여 연산 추적 방지 가능

In [ ]:
a.grad == d/a

tensor(True)